CREATE TABLE IF NOT EXISTS Tech(
    techID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    techName VARCHAR(30) NOT NULL,
    "password" TEXT NOT NULL,
    locationZip  VARCHAR(5) NOT NULL,
    techTypeID REFERENCES TechType(typeID) NOT NULL,
    rating INT,
    contactNumber VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS TechType(
    typeID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    typeName VARCHAR(30) NOT NULL,
    typeDescription TEXT
);
